language: dart

dart:
  - stable
  - dev

sudo: false

install:
  - gem install coveralls-lcov

script: ./tool/travis.sh

after_success:
  - coveralls-lcov var/lcov.info

cache:
  directories:
  - $HOME/.pub-cache
branches:
  only:
  - master