version: "3"
services:
  centrifugo:
    image: centrifugo/centrifugo:v2.3.1
    container_name: centrifugo
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/centrifugo
    command: centrifugo --config=config.json
  sign_server:
    container_name: sign_server
    build: .
    command: npm start
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000
    environment:
      - PORT=5000
