name: CI

on: [push, pull_request]

jobs:
  build:
    # Prevent duplicate builds on internal PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test compatible SDK and protobuf version combinations
        # protobuf 5.0.0+: SDK >= 3.7
        include:
          # Test with oldest SDK supported.
          - sdk: "3.7"
            protobuf: "5.0.0"
          - sdk: "3.7"
            protobuf: "6.0.0"
          # Test latest protobuf versions with SDK stable and beta
          - sdk: stable
            protobuf: "5.0.0"
          - sdk: stable
            protobuf: "6.0.0"
          - sdk: beta
            protobuf: "5.0.0"
          - sdk: beta
            protobuf: "6.0.0"
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Override protobuf version
        run: dart pub add protobuf:${{ matrix.protobuf }}

      - name: Start Centrifugo
        run: docker compose up -d --wait

      - name: Run analyzer
        run: dart analyze lib/

      - name: Run tests
        run: dart run test --reporter expanded
